2024-11-05 14:10:29,614 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\tests_12_1\rt_with_exceptions.py", line 81, in test_run
    runner_obj = Runner(name=20, speed=10)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\tests_12_1\rt_with_exceptions.py", line 15, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-05 14:10:29,617 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\tests_12_1\rt_with_exceptions.py", line 70, in test_walk
    walker_obj = Runner('Student', speed=-10)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\tests_12_1\rt_with_exceptions.py", line 20, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
